### ISSUE TITLE
Syntax issues

### ISSUE THREAD

**Issue by Vudubond** [diegocanton/cPanel_BlockMailAccountAbuse#1]
Hello,

Can you provide please cPanel/Exim version.

At me as far as Im aware the default log file is /var/log/maillog , and running the first line it doesn't give me results:

massivespammer.sh:

awk '($0 >= from)' from="$(LC_ALL=C date +'%Y-%m-%d %H:%M:%S' -d -${1}hour)" /var/log/exim_mainlog  | egrep "dovecot_[login|plain]" | egrep -v "failed|suspended|google" | sed "s/P=esmtps*a//g" | sed "s/X=.* CV=no//g" | sed "s/ (//g" | awk '{print $8 " " $7}' | awk -F":" '{print $2}' > /tmp/exim_login_

Probably it is because of the Syntax. Is it possible to Copy/Paste the syntax from your log?

At me the log is:

May  7 15:29:20 HOSTNAME dovecot: pop3-login: Login: user=<EmailAddress>, method=PLAIN, rip=209.85.217.157, lip=OurIP, mpid=3779837, session=<3dqp0ZxrXZbRVdmd>

May  7 13:21:46 HOSTNAME dovecot: imap-login: Login: user=<EmailAddress>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=1117435, secured, session=<Ut+m64ZrC7B/AAAB>- Probably Webmail Access-Which can be an issue if its not filtered.

May  7 13:21:36 HOSTNAME dovecot: imap-login: Login: user=<EmailAddress>, method=PLAIN, rip=ClientIP, lip=OurIP, mpid=1117095, session=<CrsK64ZrkrhWf+uY>

**Comment by diegocanton** [comment]
About the LOG files in cPanel:
https://documentation.cpanel.net/display/CKB/The+cPanel+Log+Files

You pointed out a log that registers POP and IMAP access, the script serves to identify SPAMMERs that abuse client accounts of their hosting, that is, to identify SPAMMERs in the output.

There are already many antispam systems that prevent SPAM from being received, but I do not see systems that prevent it from coming out. When I decided to develop this, we had already controlled the reception of SPAM with the project SPFBL (https://github.com/leonamp/SPFBL), our challenge was to avoid abuses of our clients' accounts. Something we often saw was an account sending more than 100,000 messages, all of which were accumulated in the outgoing queue.

The solution was to develop something that log analysis from time to time to identify these abused accounts, in this case the login will be SMTP.


cPanel: 56.0 to 70.34
CentOS: 6.8 to 7.4
exim: 4.87 to 4.90_1

**Comment by diegocanton** [comment]
Sobre os arquivos de LOG no cPanel:
https://documentation.cpanel.net/display/CKB/The+cPanel+Log+Files

Você apontou um log que registra acessos POP e IMAP, o script serve para identificar SPAMMERs que abusem de contas de clientes de sua hospedagem, ou seja, para identificar SPAMMERs na saida.

Já há muitos sistemas antispam que evitam a recepção de SPAM, mas não vejo sistemas que evitem a saida. Quando resolvi desenvolter isso, já haviamos controlado a recepção de SPAM com o projeto SPFBL (https://github.com/leonamp/SPFBL), nosso desafio era evitar abusos das contas de nossos clientes. Algo que viamos com certa frequencia era uma conta enviar mais de 100 mil mensagens, ficando todas acumuladas na fila de saida. 

A solução foi desenvolver algo que analise o log de tempos em tempos para identificar essas contas abusada, neste caso o login será SMTP.


cPanel: 56.0 até 70.34
CentOS: 6.8 até 7.4
exim: 4.87 até 4.90_1

**Comment by Vudubond** [comment]
Thank you, you are right, the script is fine, it is working correctly, it was a mistake on my side.

Obrigado, você está certo, o roteiro está bom, está funcionando corretamente, foi um erro do meu lado.
